language: php

php:
  - "5.6"
  - "7.0"

# sudo=false to run builds inside container infrastructure
# see https://github.com/bem/bem-components/issues/1528
sudo: false

before_script:
    - npm install

script:
    - npm run specs

env:
  global:
    - GH_REF: github.com/apwillio/ap-components.git
    - ISTANBUL_COVERAGE: yes
